# create a dev conda environment with: `make create_env` or `conda env create -f environment.yml`
name: bionc
channels:
- conda-forge
- default
dependencies:
- python = 3.11.6
- scipy
- numpy
- packaging
- casadi
- ezc3d
- pyomeca
- plotly
- dill
- bioviz
- biorbd

